name: Building

on:
  push:
    branches:
      - main
      - deploy
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  install:
    name: Install application
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          cd app/
          npm i
